/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package student;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Course;
import model.User;
import model.Utils;

/**
 *
 * @author Dell
 */
public class ViewCoursePanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewCoursePanel
     */
    JPanel mainPanel;
    Course course;
    String professorName;
    int profId;
    Utils utils;
    User user;
    public ViewCoursePanel(JPanel mainPanel, Course course, Utils utils, User user) {
        initComponents();
        this.mainPanel = mainPanel;
        this.course = course;
        this.utils = utils;
        this.user = user;
        
        txtCourseId.setText(Integer.toString(course.getID()));
        txtProfName.setText(course.getProfName());
        txtDesc.setText(course.getDescription());
        txtCourseSchedule.setText(course.getTime());
        txtCourseRanking.setText(course.getRanking());
        txtCoursePre.setText(course.getPreReq());
        txtCourseName.setText(course.getName());
        txtCourseMaterial.setText(course.getMaterial());
        txtCourseCredit.setText(Integer.toString(course.getCredits()));
        professorName = course.getProfName();
        profId = course.getProfId();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblViewCourse = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        lblCoursePre = new javax.swing.JLabel();
        txtCoursePre = new javax.swing.JTextField();
        btnProfFeedback = new javax.swing.JButton();
        lblCourseId = new javax.swing.JLabel();
        lblCourseSchedule = new javax.swing.JLabel();
        txtCourseId = new javax.swing.JTextField();
        txtCourseSchedule = new javax.swing.JTextField();
        lblCourseName = new javax.swing.JLabel();
        lblCourseMaterial = new javax.swing.JLabel();
        txtCourseName = new javax.swing.JTextField();
        txtCourseMaterial = new javax.swing.JTextField();
        lblProfName = new javax.swing.JLabel();
        lblDesc = new javax.swing.JLabel();
        txtProfName = new javax.swing.JTextField();
        txtDesc = new javax.swing.JTextField();
        lblCourseRanking = new javax.swing.JLabel();
        lblCourseCredit = new javax.swing.JLabel();
        txtCourseRanking = new javax.swing.JTextField();
        txtCourseCredit = new javax.swing.JTextField();
        btnEnroll = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(73, 77, 94));

        lblViewCourse.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblViewCourse.setForeground(new java.awt.Color(239, 234, 234));
        lblViewCourse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewCourse.setText("View Course");
        lblViewCourse.setPreferredSize(new java.awt.Dimension(140, 30));

        jScrollPane1.setBorder(null);

        jPanel1.setBackground(new java.awt.Color(73, 77, 94));

        lblCoursePre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCoursePre.setForeground(new java.awt.Color(239, 234, 234));
        lblCoursePre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCoursePre.setText("Course Prerequisite:");

        txtCoursePre.setEditable(false);

        btnProfFeedback.setText("View Professor Feedback");
        btnProfFeedback.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProfFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfFeedbackActionPerformed(evt);
            }
        });

        lblCourseId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCourseId.setForeground(new java.awt.Color(239, 234, 234));
        lblCourseId.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCourseId.setText("Course ID:");

        lblCourseSchedule.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCourseSchedule.setForeground(new java.awt.Color(239, 234, 234));
        lblCourseSchedule.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCourseSchedule.setText("Course Schedule:");

        txtCourseId.setEditable(false);
        txtCourseId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCourseIdActionPerformed(evt);
            }
        });

        txtCourseSchedule.setEditable(false);

        lblCourseName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCourseName.setForeground(new java.awt.Color(239, 234, 234));
        lblCourseName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCourseName.setText("Course Name:");

        lblCourseMaterial.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCourseMaterial.setForeground(new java.awt.Color(239, 234, 234));
        lblCourseMaterial.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCourseMaterial.setText("Course Material:");

        txtCourseName.setEditable(false);
        txtCourseName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCourseNameActionPerformed(evt);
            }
        });

        txtCourseMaterial.setEditable(false);

        lblProfName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblProfName.setForeground(new java.awt.Color(239, 234, 234));
        lblProfName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblProfName.setText("Professor Name:");

        lblDesc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDesc.setForeground(new java.awt.Color(239, 234, 234));
        lblDesc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDesc.setText("Description:");

        txtProfName.setEditable(false);

        txtDesc.setEditable(false);

        lblCourseRanking.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCourseRanking.setForeground(new java.awt.Color(239, 234, 234));
        lblCourseRanking.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCourseRanking.setText("Course Ranking:");

        lblCourseCredit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCourseCredit.setForeground(new java.awt.Color(239, 234, 234));
        lblCourseCredit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCourseCredit.setText("Course Credit:");

        txtCourseRanking.setEditable(false);

        txtCourseCredit.setEditable(false);

        btnEnroll.setBackground(new java.awt.Color(73, 77, 94));
        btnEnroll.setForeground(new java.awt.Color(239, 234, 234));
        btnEnroll.setText("ENROLL");
        btnEnroll.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEnroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrollActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCoursePre, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(lblCourseRanking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCourseName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCourseId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCourseSchedule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCourseCredit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCourseMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblProfName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEnroll, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProfName, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnProfFeedback))
                    .addComponent(txtCourseSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCourseRanking, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtCoursePre, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCourseMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCourseCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtCourseId, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnEnroll, txtCourseCredit, txtCourseId, txtCourseMaterial, txtCourseName, txtCoursePre, txtCourseRanking, txtCourseSchedule, txtDesc, txtProfName});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCourseId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCourseId, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCourseName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCourseRanking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCourseRanking, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCoursePre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCoursePre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCourseSchedule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCourseSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCourseCredit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCourseCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCourseMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCourseMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblProfName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtProfName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnProfFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEnroll, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jScrollPane1.setViewportView(jPanel1);

        btnBack.setBackground(new java.awt.Color(73, 77, 94));
        btnBack.setForeground(new java.awt.Color(239, 234, 234));
        btnBack.setText("< Back");
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblViewCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(780, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblViewCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCourseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCourseNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCourseNameActionPerformed

    private void txtCourseIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCourseIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCourseIdActionPerformed

    private void btnProfFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfFeedbackActionPerformed
        User professor = utils.getUserDetails(Integer.toString(profId));
        if(professor == null){
            JOptionPane.showMessageDialog(this, "No details for Professor");
            return;
        }
        
        ViewProfessorFeedback panel = new ViewProfessorFeedback(mainPanel, professor);
        mainPanel.add("ViewProfessorFeedback",panel);
        CardLayout layout = (CardLayout) mainPanel.getLayout();
        layout.next(mainPanel);
    }//GEN-LAST:event_btnProfFeedbackActionPerformed

    private void btnEnrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrollActionPerformed
        if(utils.enrollStudentToCourse(course, user)){
            JOptionPane.showMessageDialog(this, "Sucessfully enrolled to" + course.getName());
        }
        else{
            JOptionPane.showMessageDialog(this, "There was an issue while enrolling to " + course.getName() + " try again later");
        }
    }//GEN-LAST:event_btnEnrollActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        mainPanel.remove(this);
        CardLayout layout = (CardLayout) mainPanel.getLayout();
        layout.previous(mainPanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEnroll;
    private javax.swing.JButton btnProfFeedback;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCourseCredit;
    private javax.swing.JLabel lblCourseId;
    private javax.swing.JLabel lblCourseMaterial;
    private javax.swing.JLabel lblCourseName;
    private javax.swing.JLabel lblCoursePre;
    private javax.swing.JLabel lblCourseRanking;
    private javax.swing.JLabel lblCourseSchedule;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblProfName;
    private javax.swing.JLabel lblViewCourse;
    private javax.swing.JTextField txtCourseCredit;
    private javax.swing.JTextField txtCourseId;
    private javax.swing.JTextField txtCourseMaterial;
    private javax.swing.JTextField txtCourseName;
    private javax.swing.JTextField txtCoursePre;
    private javax.swing.JTextField txtCourseRanking;
    private javax.swing.JTextField txtCourseSchedule;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextField txtProfName;
    // End of variables declaration//GEN-END:variables
}
