/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package admin;

import model.FacultyDirectory;
import model.StudentDirectory;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import javax.swing.JPanel;
import model.Course;
import model.User;
import model.UserToCourse;
import model.Utils;

/**
 *
 * @author nitishahuja
 */
public class AdminDashboardJPanel extends javax.swing.JPanel {
    private JPanel mainPanel;
    private FacultyDirectory facultyDirectory;
    private StudentDirectory studentDirectory;
    
    /**
     * Creates new form AdminDashboard
     */
    User user;
    Utils utils;
    ArrayList<Integer> courseIds;
    List<String> uniqueProfNamesList;
    ArrayList<UserToCourse> studentList;
    public AdminDashboardJPanel(JPanel mainPanel, User user, Utils utils) {
        this.courseIds = new ArrayList<>();
        uniqueProfNamesList = new ArrayList<>();
        studentList = utils.getAllStudents();
        initComponents();
        this.mainPanel = mainPanel;
        this.user = user;
        this.utils = utils;
        
        PopulateBox();
//                this.facultyDirectory = facultyDirectory;
//                this.studentDirectory = studentDirectory;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        cbCourse = new javax.swing.JComboBox<>();
        studentCardPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblStudentNumber = new javax.swing.JLabel();
        professorCardPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblProfessorNumber = new javax.swing.JLabel();
        lblSelectCourse = new javax.swing.JLabel();

        setBackground(new java.awt.Color(73, 77, 94));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin Dashboard");

        jButton2.setBackground(new java.awt.Color(73, 77, 94));
        jButton2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(239, 234, 234));
        jButton2.setText("Manage Students");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(73, 77, 94));
        jButton3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(239, 234, 234));
        jButton3.setText("Manage Faculty");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        cbCourse.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbCourseItemStateChanged(evt);
            }
        });
        cbCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbCourseMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Students");

        lblStudentNumber.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblStudentNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStudentNumber.setText("0");

        javax.swing.GroupLayout studentCardPanelLayout = new javax.swing.GroupLayout(studentCardPanel);
        studentCardPanel.setLayout(studentCardPanelLayout);
        studentCardPanelLayout.setHorizontalGroup(
            studentCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblStudentNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        studentCardPanelLayout.setVerticalGroup(
            studentCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentCardPanelLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblStudentNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Professor");

        lblProfessorNumber.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblProfessorNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProfessorNumber.setText("0");

        javax.swing.GroupLayout professorCardPanelLayout = new javax.swing.GroupLayout(professorCardPanel);
        professorCardPanel.setLayout(professorCardPanelLayout);
        professorCardPanelLayout.setHorizontalGroup(
            professorCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblProfessorNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(professorCardPanelLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        professorCardPanelLayout.setVerticalGroup(
            professorCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(professorCardPanelLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblProfessorNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblSelectCourse.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblSelectCourse.setForeground(new java.awt.Color(255, 255, 255));
        lblSelectCourse.setText("Select Course:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSelectCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                            .addComponent(studentCardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(professorCardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(312, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton2, jButton3});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSelectCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(professorCardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(studentCardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton2, jButton3});

    }// </editor-fold>//GEN-END:initComponents

    private void PopulateBox(){
        var courses = utils.getCourse();
        //Unique values
        HashSet<String> uniqueProfNames = new HashSet<>();
        for (Course course : courses) {
            uniqueProfNames.add(course.getProfName());
        }

        uniqueProfNamesList = new ArrayList<>(uniqueProfNames);
        
        cbCourse.addItem("All");
        for(Course c: courses){
            cbCourse.addItem(c.getName());
        }
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ManageFacultyJPanel panel = new ManageFacultyJPanel(mainPanel, user, utils);
        mainPanel.add("ManageFacultyJPanel", panel);
        CardLayout layout = (CardLayout) mainPanel.getLayout();
        layout.next(mainPanel);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ManageStudentJPanel panel = new ManageStudentJPanel(mainPanel, user ,utils, studentList);
        mainPanel.add("ManageStudentJPanel", panel);
        CardLayout layout = (CardLayout) mainPanel.getLayout();
        layout.next(mainPanel);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbCourseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbCourseItemStateChanged
        var students = 0;
        String selectedItem = cbCourse.getSelectedItem().toString();
        var courses = utils.getCoursesByCourseName(selectedItem);
        if(selectedItem.equals("All")){
            lblProfessorNumber.setText(Integer.toString(uniqueProfNamesList.size()));
        }else{
            lblProfessorNumber.setText(Integer.toString(courses.size()));    
        }
        for(Course c: courses){
            HashSet<String> uniqueStudentList = new HashSet<>();
            ArrayList<UserToCourse> studentsList = utils.getStudentsByCourseId(c.getID());
            
            for (UserToCourse userToCourse : studentList) {
                uniqueStudentList.add(Integer.toString(userToCourse.getUserID()));
            }

            var newUniqueStudentList = new ArrayList<>(uniqueStudentList);
            students = students + newUniqueStudentList.size();
        }
        //TODO: Update this Function
        if(selectedItem.equals("All")){
            HashSet<String> uniqueStudentList = new HashSet<>();
            for (UserToCourse userToCourse : studentList) {
                uniqueStudentList.add(Integer.toString(userToCourse.getUserID()));
            }

            var newUniqueStudentList = new ArrayList<>(uniqueStudentList);
        
            lblStudentNumber.setText(Integer.toString(newUniqueStudentList.size())); 
        }
        else{
            lblStudentNumber.setText(Integer.toString(students)); 
        }
    }//GEN-LAST:event_cbCourseItemStateChanged

    private void cbCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbCourseMouseClicked

    }//GEN-LAST:event_cbCourseMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbCourse;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblProfessorNumber;
    private javax.swing.JLabel lblSelectCourse;
    private javax.swing.JLabel lblStudentNumber;
    private javax.swing.JPanel professorCardPanel;
    private javax.swing.JPanel studentCardPanel;
    // End of variables declaration//GEN-END:variables
}
