/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package common;

import admin.AdminDashboardJPanel;
import java.awt.CardLayout;
import model.UserDirectory;
import javax.swing.JOptionPane;
import model.User;
import model.Utils;
import student.StudentDashboardPanel;
import teacher.ProfessorDashboardJPanel;
import transcript.AuthorityDashboard;
/**
 *
 * @author Dell
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    UserDirectory users;
    Utils utils;
    public MainJFrame() {
        initComponents();
        users = new UserDirectory();
        this.utils = new Utils();
        btnLogout.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        navigationPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        loginPanel = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        lblUnlock = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        txttype = new javax.swing.JComboBox<>();
        txtusername = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnSignUp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        splitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        navigationPanel.setBackground(new java.awt.Color(73, 77, 94));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(239, 234, 234));
        jLabel2.setText("Digital Education Platform");

        btnLogout.setBackground(new java.awt.Color(73, 77, 94));
        btnLogout.setForeground(new java.awt.Color(239, 234, 234));
        btnLogout.setText("LOGOUT");
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navigationPanelLayout = new javax.swing.GroupLayout(navigationPanel);
        navigationPanel.setLayout(navigationPanelLayout);
        navigationPanelLayout.setHorizontalGroup(
            navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navigationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                .addGap(223, 223, 223)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        navigationPanelLayout.setVerticalGroup(
            navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        splitPane.setTopComponent(navigationPanel);

        mainPanel.setBackground(new java.awt.Color(73, 77, 94));
        mainPanel.setLayout(new java.awt.CardLayout());

        loginPanel.setBackground(new java.awt.Color(73, 77, 94));

        jSeparator3.setBackground(new java.awt.Color(239, 234, 234));
        jSeparator3.setForeground(new java.awt.Color(239, 234, 234));

        jSeparator4.setBackground(new java.awt.Color(239, 234, 234));
        jSeparator4.setForeground(new java.awt.Color(239, 234, 234));

        lblUnlock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/unlock.png"))); // NOI18N

        lblUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/user.png"))); // NOI18N

        txttype.setBackground(new java.awt.Color(73, 77, 94));
        txttype.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txttype.setForeground(new java.awt.Color(239, 234, 234));
        txttype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student", "Teacher", "Admin", "TranscriptAdmin" }));

        txtusername.setBackground(new java.awt.Color(73, 77, 94));
        txtusername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtusername.setForeground(new java.awt.Color(239, 234, 234));
        txtusername.setToolTipText("Username");
        txtusername.setBorder(null);

        txtpassword.setBackground(new java.awt.Color(73, 77, 94));
        txtpassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtpassword.setForeground(new java.awt.Color(239, 234, 234));
        txtpassword.setToolTipText("Password");
        txtpassword.setBorder(null);

        btnLogin.setBackground(new java.awt.Color(73, 77, 94));
        btnLogin.setForeground(new java.awt.Color(239, 234, 234));
        btnLogin.setText("LOGIN");
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(239, 234, 234));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Login");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(239, 234, 234));
        jLabel8.setText("Create Account?");

        btnSignUp.setBackground(new java.awt.Color(73, 77, 94));
        btnSignUp.setForeground(new java.awt.Color(239, 234, 234));
        btnSignUp.setText("SIGN UP");
        btnSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(319, 319, 319)
                .addComponent(lblUser)
                .addGap(18, 18, 18)
                .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(367, 367, 367)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(319, 319, 319)
                .addComponent(lblUnlock)
                .addGap(18, 18, 18)
                .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(367, 367, 367)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(367, 367, 367)
                .addComponent(txttype, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(367, 367, 367)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(319, 319, 319)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(btnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblUser))
                    .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblUnlock))
                    .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txttype, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8))
                    .addComponent(btnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        mainPanel.add(loginPanel, "card2");

        splitPane.setRightComponent(mainPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        //Get input data.
        String username = txtusername.getText();
        String password = new String (txtpassword.getPassword());
        String type = txttype.getSelectedItem().toString();

        if(username.isEmpty() && password.isEmpty()){
            JOptionPane.showMessageDialog(this, "All fields are mandatory");
            return;
        }
        String hasedPassword = utils.hashPassword(password);
        User user = users.containsUser(username, hasedPassword, type);
        if(user != null){
            switch (type) {
                case "Student" -> {
                    StudentDashboardPanel panel = new StudentDashboardPanel(mainPanel, users, user, utils);
                    mainPanel.add("StudentDashboardPanel",panel);
                    CardLayout layout = (CardLayout) mainPanel.getLayout();
                    layout.next(mainPanel);
                    btnLogout.setVisible(true);
                }
                case "Teacher" -> {
                    ProfessorDashboardJPanel panel = new ProfessorDashboardJPanel(mainPanel, user, utils);
                    mainPanel.add("ProfessorDashboardJPanel",panel);
                    CardLayout layout = (CardLayout) mainPanel.getLayout();
                    layout.next(mainPanel);
                    btnLogout.setVisible(true);
                }
                case "Admin" -> {
                    AdminDashboardJPanel panel = new AdminDashboardJPanel(mainPanel, user, utils);
                    mainPanel.add("AdminDashboardJPanel",panel);
                    CardLayout layout = (CardLayout) mainPanel.getLayout();
                    layout.next(mainPanel);
                    btnLogout.setVisible(true);
                }
                case "TranscriptAdmin" -> {
                    AuthorityDashboard panel = new AuthorityDashboard(mainPanel, utils);
                    mainPanel.add("AdminDashboardJPanel",panel);
                    CardLayout layout = (CardLayout) mainPanel.getLayout();
                    layout.next(mainPanel);
                    btnLogout.setVisible(true);
                }
                default -> {
                    JOptionPane.showMessageDialog(this, "Invalid User Type");
                }
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Username or Password in Invalid", "Error", JOptionPane.ERROR_MESSAGE);
        }

        //Get data from DB and check
        //        try{
            //            //SQL Connection
            //            Class.forName("com.mysql.cj.jdbc.Driver");
            //            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/digitaleducationsystem","root","monilshah");
            //
            //
            //            //Query SQL
            //            Statement stm = con.createStatement();
            //            String sql = "SELECT * FROM USERS WHERE USERNAME='"+username+"' and PASSWORD='"+password+"' and TYPE='"+type+"'";
            //            ResultSet rs = stm.executeQuery(sql);
            //            if(rs.next()){
                //
                //                switch (type) {
                    //                    case "Student" -> {
                        //                        StudentDashboardPanel panel = new StudentDashboardPanel(mainPanel);
                        //                        mainPanel.add("StudentDashboardPanel",panel);
                        //                        CardLayout layout = (CardLayout) mainPanel.getLayout();
                        //                        layout.next(mainPanel);
                        //                    }
                    //                    case "Teacher" -> {
                        //                        ProfessorDashboardJPanel panel = new ProfessorDashboardJPanel(mainPanel);
                        //                        mainPanel.add("ProfessorDashboardJPanel",panel);
                        //                        CardLayout layout = (CardLayout) mainPanel.getLayout();
                        //                        layout.next(mainPanel);
                        //                    }
                    //                    case "Admin" -> {
                        ////                        AdminDashboardJPanel panel = new AdminDashboardJPanel(mainPanel);
                        ////                        mainPanel.add("AdminDashboardJPanel",panel);
                        ////                        CardLayout layout = (CardLayout) mainPanel.getLayout();
                        ////                        layout.next(mainPanel);
                        //                    }
                    //                    default -> {
                        //                            JOptionPane.showMessageDialog(this, "Invalid User Type");
                        //                    }
                    //                }
                //            }else{
                //                JOptionPane.showMessageDialog(this, "Username or Password in Invalid");
                //            }
            //
            //        }
        //        catch(ClassNotFoundException | SQLException e){
            //            System.out.println("There has been an issue while logging in");
            //            System.out.println(e.getMessage());
            //        }
        //                StudentDashboardPanel panel = new StudentDashboardPanel(mainPanel);
        //                mainPanel.add("StudentDashboardPanel",panel);
        //                CardLayout layout = (CardLayout) mainPanel.getLayout();
        //                layout.next(mainPanel);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        SignUpPanel signUpPanel = new SignUpPanel(mainPanel, users, utils);
        mainPanel.add("SignUpPanel", signUpPanel);
        CardLayout layout = (CardLayout) mainPanel.getLayout();
        layout.next(mainPanel);
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.add("LoginPanel",loginPanel);
        CardLayout layout = (CardLayout) mainPanel.getLayout();
        layout.next(mainPanel);
        btnLogout.setVisible(false);
        txtpassword.setText("");
        txtusername.setText("");
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblUnlock;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel navigationPanel;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JComboBox<String> txttype;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
