/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package teacher;

import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Assignment;
import model.Course;
import model.User;
import model.Utils;

/**
 *
 * @author rachanakeshav
 */
public class ManageCourseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageCourseJPanel
     */
    private JPanel mainPanel;
    User user;
    Utils utils;
    Course selectedCourse;
    public ManageCourseJPanel(JPanel mainPanel, User user, Utils utils) {
        initComponents();
        this.mainPanel= mainPanel;
        this.utils = utils;
        this.user = user;
        PopulateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourseList = new javax.swing.JTable();
        btnManage = new javax.swing.JButton();
        lblSelect = new javax.swing.JLabel();
        btnHost = new javax.swing.JButton();
        btnCreateAssignment = new javax.swing.JButton();
        btnBack1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(73, 77, 94));

        lblHeader.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(239, 234, 234));
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Manage Course");

        tblCourseList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course ID", "Course Name", "Course Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCourseList);
        if (tblCourseList.getColumnModel().getColumnCount() > 0) {
            tblCourseList.getColumnModel().getColumn(0).setResizable(false);
            tblCourseList.getColumnModel().getColumn(1).setResizable(false);
            tblCourseList.getColumnModel().getColumn(2).setResizable(false);
        }

        btnManage.setText("Manage Students");
        btnManage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageActionPerformed(evt);
            }
        });

        lblSelect.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblSelect.setForeground(new java.awt.Color(239, 234, 234));
        lblSelect.setText("Select course:");

        btnHost.setText("Host");
        btnHost.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHostActionPerformed(evt);
            }
        });

        btnCreateAssignment.setText("Create Assignment");
        btnCreateAssignment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCreateAssignment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAssignmentActionPerformed(evt);
            }
        });

        btnBack1.setBackground(new java.awt.Color(73, 77, 94));
        btnBack1.setForeground(new java.awt.Color(239, 234, 234));
        btnBack1.setText("< Back");
        btnBack1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(btnManage, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(138, 138, 138)
                        .addComponent(btnHost, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 366, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCreateAssignment, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(91, 91, 91))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnHost, btnManage});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblHeader)
                .addGap(42, 42, 42)
                .addComponent(lblSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManage, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHost, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreateAssignment, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public void PopulateTable(){
        DefaultTableModel tbl = (DefaultTableModel) tblCourseList.getModel();
        tbl.setRowCount(0);
        for(Course c : utils.getCoursesWithProfID(user.getId())){
            Object[] row = new Object[4];
            row[0] = c;
            row[1] = c.getName();
            row[2] = c.getTime();
            
            tbl.addRow(row);
        }
    }
        
    private void btnManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageActionPerformed
        //Get select Record
        int selectedRowIndex = tblCourseList.getSelectedRow();

        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please Select a row to view.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblCourseList.getModel();
        Object vitalSigns = (Course) model.getValueAt(selectedRowIndex, 0);

        if(vitalSigns instanceof Course c){
            selectedCourse = c;
            // TODO add your handling code here:
            ManageStudentsScoreJPanel panel = new ManageStudentsScoreJPanel(mainPanel, c, utils);
            mainPanel.add("ManageStudentsScoreJPanel", panel);
            CardLayout layout = (CardLayout) mainPanel.getLayout();
            layout.next(mainPanel);
        }
        else{
            JOptionPane.showMessageDialog(this, "Invalid data in the selected row.");
        }
        

        
    }//GEN-LAST:event_btnManageActionPerformed

    private void btnHostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHostActionPerformed
        
        //Get the current course
        int selectedRowIndex = tblCourseList.getSelectedRow();

        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please Select a row to view.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblCourseList.getModel();
        Object vitalSigns = (Course) model.getValueAt(selectedRowIndex, 0);

        if(vitalSigns instanceof Course c){
            HostMeetingJPanel panel = new HostMeetingJPanel(mainPanel, utils, c);
            mainPanel.add("HostMeetingJPanel", panel);
            CardLayout layout = (CardLayout) mainPanel.getLayout();
            layout.next(mainPanel);
        }
        else{
            JOptionPane.showMessageDialog(this, "Invalid data in the selected row.");
        }
        
        
    }//GEN-LAST:event_btnHostActionPerformed

    private void btnCreateAssignmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAssignmentActionPerformed
        // TODO add your handling code here:
                //Get the current course
        int selectedRowIndex = tblCourseList.getSelectedRow();

        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please Select a row to view.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblCourseList.getModel();
        Object vitalSigns = (Course) model.getValueAt(selectedRowIndex, 0);

        if(vitalSigns instanceof Course c){
            CreateAssignmentJPanel panel = new CreateAssignmentJPanel(mainPanel, user ,utils, c);
            mainPanel.add("CreateAssignmentJPanel", panel);
            CardLayout layout = (CardLayout) mainPanel.getLayout();
            layout.next(mainPanel);
        }
        else{
            JOptionPane.showMessageDialog(this, "Invalid data in the selected row.");
        }

    }//GEN-LAST:event_btnCreateAssignmentActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        mainPanel.remove(this);
        CardLayout layout = (CardLayout) mainPanel.getLayout();
        layout.previous(mainPanel);
    }//GEN-LAST:event_btnBack1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnCreateAssignment;
    private javax.swing.JButton btnHost;
    private javax.swing.JButton btnManage;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblSelect;
    private javax.swing.JTable tblCourseList;
    // End of variables declaration//GEN-END:variables
}
