/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package teacher;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Course;
import model.UserToCourse;
import model.Utils;

/**
 *
 * @author rachanakeshav
 */
public class ManageStudentsScoreJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageStudentsScoreJPanel
     */
    private JPanel mainPanel;
    private Course course;
    private Utils utils;
    private int userToCourseId;
    public ManageStudentsScoreJPanel(JPanel mainPanel, Course course, Utils utils) {
        initComponents();
        this.mainPanel= mainPanel;
        this.course = course;
        this.utils=utils;
        this.userToCourseId = 0;
        populateDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSelectedCourse = new javax.swing.JLabel();
        txtSelectedCourse = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudentList = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        lblScore = new javax.swing.JLabel();
        lblStudentID = new javax.swing.JLabel();
        txtScore = new javax.swing.JTextField();
        txtStudentID = new javax.swing.JTextField();
        btnUpdateScore = new javax.swing.JButton();
        lblStudentName = new javax.swing.JLabel();
        txtStudentName = new javax.swing.JTextField();
        lblScore1 = new javax.swing.JLabel();
        txtRemark = new javax.swing.JTextField();
        lblHeader = new javax.swing.JLabel();
        btnBack1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(73, 77, 94));

        lblSelectedCourse.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblSelectedCourse.setForeground(new java.awt.Color(239, 234, 234));
        lblSelectedCourse.setText("Selected Course: ");

        txtSelectedCourse.setEditable(false);

        tblStudentList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Student ID", "Student Name", "Attendance", "Score", "Completed"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblStudentList);
        if (tblStudentList.getColumnModel().getColumnCount() > 0) {
            tblStudentList.getColumnModel().getColumn(0).setResizable(false);
            tblStudentList.getColumnModel().getColumn(1).setResizable(false);
            tblStudentList.getColumnModel().getColumn(2).setResizable(false);
            tblStudentList.getColumnModel().getColumn(3).setResizable(false);
            tblStudentList.getColumnModel().getColumn(4).setResizable(false);
            tblStudentList.getColumnModel().getColumn(5).setResizable(false);
        }

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        lblScore.setForeground(new java.awt.Color(239, 234, 234));
        lblScore.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblScore.setText("Score:");

        lblStudentID.setForeground(new java.awt.Color(239, 234, 234));
        lblStudentID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblStudentID.setText("Student ID:");

        txtStudentID.setEditable(false);
        txtStudentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentIDActionPerformed(evt);
            }
        });

        btnUpdateScore.setBackground(new java.awt.Color(0, 153, 0));
        btnUpdateScore.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdateScore.setForeground(new java.awt.Color(239, 234, 234));
        btnUpdateScore.setText("Mark Course As Completed");
        btnUpdateScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateScoreActionPerformed(evt);
            }
        });

        lblStudentName.setForeground(new java.awt.Color(239, 234, 234));
        lblStudentName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblStudentName.setText("Student Name:");

        txtStudentName.setEditable(false);

        lblScore1.setForeground(new java.awt.Color(239, 234, 234));
        lblScore1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblScore1.setText("Remarks");

        lblHeader.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(239, 234, 234));
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Manage Student");

        btnBack1.setBackground(new java.awt.Color(73, 77, 94));
        btnBack1.setForeground(new java.awt.Color(239, 234, 234));
        btnBack1.setText("< Back");
        btnBack1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 894, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblSelectedCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtSelectedCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblStudentName)
                                        .addComponent(lblStudentID)
                                        .addComponent(lblScore, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblScore1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtScore)
                                        .addComponent(txtStudentName)
                                        .addComponent(txtRemark)
                                        .addComponent(btnUpdateScore, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                        .addComponent(txtStudentID)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblHeader)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSelectedCourse, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(lblSelectedCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStudentID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentName)
                    .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblScore)
                    .addComponent(txtScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblScore1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtRemark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdateScore, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblScore, lblStudentID, lblStudentName, txtRemark, txtScore, txtStudentID, txtStudentName});

    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateScoreActionPerformed
        // TODO add your handling code here:
        int score= Integer.parseInt(txtScore.getText());
        String remark = txtRemark.getText();
        boolean isUpdated = utils.UpdateStudentScore(score, remark, Integer.parseInt(Integer.toString(userToCourseId)));
        if(isUpdated){
            JOptionPane.showMessageDialog(this, "Student score updated successfully.");
            populateDetails();
        }
        else JOptionPane.showMessageDialog(this, "Could not update the score. Please try again.");
        
    }//GEN-LAST:event_btnUpdateScoreActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        //Get select Record
        int selectedRowIndex = tblStudentList.getSelectedRow();

        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please Select a row to view.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblStudentList.getModel();
        Object vitalSigns = (UserToCourse) model.getValueAt(selectedRowIndex, 0);

        if(vitalSigns instanceof UserToCourse c){
            // TODO add your handling code here:
            userToCourseId = c.getID();
            txtStudentID.setText(Integer.toString(c.getUserID()));
            txtStudentName.setText(c.getStudentName());
            txtScore.setText(Integer.toString(c.getScore()));
        }
        else{
            JOptionPane.showMessageDialog(this, "Invalid data in the selected row.");
        }
    }//GEN-LAST:event_btnViewActionPerformed

    private void txtStudentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentIDActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        mainPanel.remove(this);
        CardLayout layout = (CardLayout) mainPanel.getLayout();
        layout.previous(mainPanel);
    }//GEN-LAST:event_btnBack1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnUpdateScore;
    private javax.swing.JButton btnView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblScore;
    private javax.swing.JLabel lblScore1;
    private javax.swing.JLabel lblSelectedCourse;
    private javax.swing.JLabel lblStudentID;
    private javax.swing.JLabel lblStudentName;
    private javax.swing.JTable tblStudentList;
    private javax.swing.JTextField txtRemark;
    private javax.swing.JTextField txtScore;
    private javax.swing.JTextField txtSelectedCourse;
    private javax.swing.JTextField txtStudentID;
    private javax.swing.JTextField txtStudentName;
    // End of variables declaration//GEN-END:variables

    private void populateDetails() {
        txtSelectedCourse.setText(course.getName());
        DefaultTableModel tbl = (DefaultTableModel) tblStudentList.getModel();
        tbl.setRowCount(0);
        for(UserToCourse c : utils.getStudentsByCourseId(course.getID())){
            Object[] row = new Object[6];
            row[0] = c;
            row[1] = c.getUserID();
            row[2] = c.getStudentName();
            row[3] = c.getAttendance();
            row[4] = c.getScore();
            row[5] = c.isCompleted();
            
            tbl.addRow(row);
        }
    }
}
