/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package teacher;

import java.awt.CardLayout;
import javax.swing.JPanel;
import model.User;
import model.Utils;

/**
 *
 * @author rachanakeshav
 */
public class ProfessorDashboardJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProfessorDashboardJPanel
     */
    JPanel mainPanel;
    User user;
    Utils utils;
    public ProfessorDashboardJPanel(JPanel mainPanel, User user, Utils utils) {
        initComponents();
        this.mainPanel= mainPanel;
        this.user = user;
        this.utils = utils;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        action1Panel = new javax.swing.JPanel();
        lblViewProfile = new javax.swing.JLabel();
        action2Panel = new javax.swing.JPanel();
        lblCreateCourse = new javax.swing.JLabel();
        action3Panel = new javax.swing.JPanel();
        lblManageCourse = new javax.swing.JLabel();
        lblProfessorDashboard = new javax.swing.JLabel();

        setBackground(new java.awt.Color(73, 77, 94));

        action1Panel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 3, new java.awt.Color(153, 153, 153)));
        action1Panel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        action1Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                action1PanelMouseClicked(evt);
            }
        });

        lblViewProfile.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblViewProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewProfile.setText("View Profile");

        javax.swing.GroupLayout action1PanelLayout = new javax.swing.GroupLayout(action1Panel);
        action1Panel.setLayout(action1PanelLayout);
        action1PanelLayout.setHorizontalGroup(
            action1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(action1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblViewProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        action1PanelLayout.setVerticalGroup(
            action1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, action1PanelLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(lblViewProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        action2Panel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 3, new java.awt.Color(153, 153, 153)));
        action2Panel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        action2Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                action2PanelMouseClicked(evt);
            }
        });

        lblCreateCourse.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblCreateCourse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreateCourse.setText("Create Course");

        javax.swing.GroupLayout action2PanelLayout = new javax.swing.GroupLayout(action2Panel);
        action2Panel.setLayout(action2PanelLayout);
        action2PanelLayout.setHorizontalGroup(
            action2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCreateCourse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        action2PanelLayout.setVerticalGroup(
            action2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(action2PanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(lblCreateCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        action3Panel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 3, new java.awt.Color(153, 153, 153)));
        action3Panel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        action3Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                action3PanelMouseClicked(evt);
            }
        });

        lblManageCourse.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblManageCourse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManageCourse.setText("Manage Course");

        javax.swing.GroupLayout action3PanelLayout = new javax.swing.GroupLayout(action3Panel);
        action3Panel.setLayout(action3PanelLayout);
        action3PanelLayout.setHorizontalGroup(
            action3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblManageCourse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        action3PanelLayout.setVerticalGroup(
            action3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, action3PanelLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(lblManageCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        lblProfessorDashboard.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblProfessorDashboard.setForeground(new java.awt.Color(239, 234, 234));
        lblProfessorDashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProfessorDashboard.setText("Professor Dashboard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(action1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(action2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(action3Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
            .addComponent(lblProfessorDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblProfessorDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(action1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(action2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(action3Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(279, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {action1Panel, action2Panel, action3Panel});

    }// </editor-fold>//GEN-END:initComponents

    private void action1PanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_action1PanelMouseClicked
        // TODO add your handling code here:
        ViewProfessorProfileJPanel panel = new ViewProfessorProfileJPanel(mainPanel, user, utils);
        mainPanel.add("ViewProfessorProfileJPanel",panel);
        CardLayout layout = (CardLayout) mainPanel.getLayout();
        layout.next(mainPanel);
        
    }//GEN-LAST:event_action1PanelMouseClicked

    private void action2PanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_action2PanelMouseClicked
        // TODO add your handling code here:
        CreateCoursesJPanel panel = new CreateCoursesJPanel(mainPanel, user, utils);
        mainPanel.add("CreateCoursesJPanel",panel);
        CardLayout layout = (CardLayout) mainPanel.getLayout();
        layout.next(mainPanel);
    }//GEN-LAST:event_action2PanelMouseClicked

    private void action3PanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_action3PanelMouseClicked
        // TODO add your handling code here:
        ManageCourseJPanel panel = new ManageCourseJPanel(mainPanel, user, utils);
        mainPanel.add("ManageCourseJPanel",panel);
        CardLayout layout = (CardLayout) mainPanel.getLayout();
        layout.next(mainPanel);
    }//GEN-LAST:event_action3PanelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel action1Panel;
    private javax.swing.JPanel action2Panel;
    private javax.swing.JPanel action3Panel;
    private javax.swing.JLabel lblCreateCourse;
    private javax.swing.JLabel lblManageCourse;
    private javax.swing.JLabel lblProfessorDashboard;
    private javax.swing.JLabel lblViewProfile;
    // End of variables declaration//GEN-END:variables
}
